[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask-cors==5.0.0",
    "flask==3.1.0",
    "pandas==2.2.3",
    "matplotlib==3.9.3",
    "seaborn==0.13.2",
    "scikit-learn==1.5.2",
    "pyyaml>=6.0.2",
]
